### ISSUE TITLE
Falsely assume that the session is still valid on paypal redirect

### ISSUE THREAD

**Issue by tomzi8571** [wirecard/sap-commerce-ee#17]
Some customer experience a 'Server Error' when coming being redirected from paypal to hybris.
`INFO  [hybrisHTTP32] [WirecardReturnController] Received paypal return call
INFO  [hybrisHTTP32] [DefaultWirecardPaymentConverter] Signature validation with certificate 149313514698068840558925582337255664944
INFO  [hybrisHTTP32] [DefaultWirecardHopPaymentOperationsFacade] staring operation of null AUTHORIZATION_RETURN for cart code 0000038000
Mar 19, 2020 8:35:58 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [DispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
        at com.wirecard.hybris.core.strategy.impl.DefaultWirecardPaymentOperationStrategy.getOperation(DefaultWirecardPaymentOperationStrategy.java:59)
        at com.wirecard.hybris.facades.impl.DefaultWirecardHopPaymentOperationsFacade.executePaymentOperation(DefaultWirecardHopPaymentOperationsFacade.java:138)
        at com.wirecard.hybris.facades.impl.DefaultWirecardHopPaymentOperationsFacade.executePaymentOperation(DefaultWirecardHopPaymentOperationsFacade.java:114)
        at com.wirecard.hybris.addon.controllers.pages.checkout.WirecardReturnController.executePaymentOperation(WirecardReturnController.java:202)
        at com.wirecard.hybris.addon.controllers.pages.checkout.WirecardReturnController.getReturnResultURL(WirecardReturnController.java:186)
        at com.wirecard.hybris.addon.controllers.pages.checkout.WirecardReturnController.processReturn(WirecardReturnController.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`
Apparently in line
https://github.com/wirecard/sap-commerce-ee/blob/13ace5ee5753289a569d0fe727800ea5699383ec/ext-wirecard/wirecardcore/src/com/wirecard/hybris/facades/impl/DefaultWirecardHopPaymentOperationsFacade.java#L114
a new session cart is created via getCartService().getSessionCart() and this cart does not yet have a paymentMode set (== null).
What probably should happen here instead, to make sure, that the correct cart is being retrieved according to the Payment response data, eg via the requestId which is stored on the PaymentTransaction rather than assuming the user session is still alive... At least this should probably be the fallback behaviour.

**Comment by tomzi8571** [comment]
Maybe an implementation like this could be part of the solution. Find the cart that is referenced in the payment payload:
Instead of 
`@Override
    public Payment executePaymentOperation(String operation, PaymentOperationData data) throws
        WirecardPaymenException {
return executePaymentOperation(operation, data, getCartService().getSessionCart());
}
`
do this:
`    @Override
    public Payment executePaymentOperation(String operation, PaymentOperationData data) throws
        WirecardPaymenException {
        AbstractOrderModel orderModel = data.getPayment()
                                            .getCustomFields()
                                            .getCustomField()
                                            .stream()
                                            .filter(field -> "order-code".equals(field.getFieldName()))
                                            .findFirst()
                                            .flatMap(orderCodeCustomField -> abstractOrderGenericDao.find(Collections.singletonMap(
                                                AbstractOrderModel.CODE,
                                                orderCodeCustomField.getFieldValue())).stream().findFirst())
                                            .orElse(getCartService().getSessionCart());

        return executePaymentOperation(operation, data, orderModel);
    }`

**Comment by tomzi8571** [comment]
Alternatively, since the user session is lost, we could just check for a session an throw an exception thus gracefully returning to the storefront... since no session available and the default errorUrl is somewhere within checkout you will be redirected to the login page...
```
    @Override
    public Payment executePaymentOperation(String operation, PaymentOperationData data) throws
        WirecardPaymenException {
        if (getCartService().hasSessionCart()) {
            return executePaymentOperation(operation, data, getCartService().getSessionCart());
        } else {
            LOG.error("User {} has no session anymore for transaction {}", data.getPayment().getAccountHolder().getEmail(), data.getPayment().getTransactionId());
            throw new WirecardPaymenException("User has no session anymore");
        }
    }
```

**Comment by jakubpolomsky** [comment]
Thank you for the report. I have looked into the issue and noticed, that this can be mitigated in a different way as well. The WirecardReturnController is calling the executePaymentOperation(String, PaymentOperationData) . It assumes, the OrderModel contains all necessary information in the session which is not true when you log out during the process. Therefore a "simple" check within the WirecardReturnController for the session should reveal whether we should try to read out the orderId and use the executePaymentOperation(String, PaymentOperationData, String) instead or continue using the current executePaymentOperation(String, PaymentOperationData) method.

I really want to thank you for finding this and I will forward the solution proposal to our integration team to include this in one of our next releases. Sorry for the late response!

**Comment by chpro** [comment]
Further investigation showed that the sesson was only lost due to changes in chrome. Be aware  that change was suspended durring covid crisis but will be reanabled.

By default the cookies which have no SameSite attribute are now treated as SameSite=Lax not as before SameSite=None. Hence, you have to set the SameSite policy to avoid strange behavior.

See https://www.neowin.net/news/chrome-80-arrives-today-with-potentially-site-breaking-cookie-changes/ for more information.

Due to the fact that the last hop from Wirecard back to the storefront is a POST request the session cookie was not send along.

The `POST` is NOT a safe HTTP method, so browser correctly WON'T send the `SameSite=Lax` cookies. So JSESSIONID won't be sent.

Exception: Be aware of the "Lax + Post mitigation". A cookie that is at most 2 minutes old will be sent on a top-level cross-site POST request. So yes, the JSESSIONID may be sent if you're fast enough

I think this issue should be fixed on SAP site in the platform see also https://jira.hybris.com/browse/ECP-4711 and maybe also to change the POST to a GET on wirecard site if possible.
